name: Generate Video on Trello Changes

on:
  repository_dispatch:
    types: [trigger_build]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Switch to main branch
        run: |
          git checkout main
          git pull origin main

      - name: Run the video generation script
        run: |
          echo "Generating video based on Trello changes..."
          npm install
          npm run build

      - name: Set up Git user
        run: |
          git config --global user.email "mdadilsharif5@gmail.com"
          git config --global user.name "AdilSharif5"

      - name: Switch to generated-videos branch
        run: |
          git checkout -b generated-videos || git checkout generated-videos

      - name: Pull latest changes
        run: |
          git pull origin generated-videos --rebase

      - name: Add new generated video
        run: |
          git add out/video.mp4
          git commit -m "Add new generated video"

      - name: Push changes
        run: |
          git push origin generated-videos
